# NumPy Arrays

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4]
a1=np.array(lst)
lst

[1, 2, 3, 4]

In [3]:
print(a1)

[1 2 3 4]


In [ ]:
a1

In [ ]:
lst = [1,2,3,4]
a1=np.array(lst)
lst+2
# in list,it will generate error but will be executed in arrays.

In [ ]:
a1+2

# Ways to create NumPy Arrays

## 1. array()function can be used to create array-

In [ ]:
narl=np.array([2,5.2,1.0])
narl

### creating array by specifying own datatype-

In [ ]:
l=[1,2,3,4]
ar=np.array(l,dtype=np.int64)
ar

### To check type,dtype and size-

In [ ]:
l=[1,2,3,4]
ar=np.array(l,dtype=np.int64)
ar

In [ ]:
print(type(ar))

print(ar.dtype)

In [ ]:
print(ar.itemsize)

In [ ]:
ad={1:"A",2:"B",3:"C",4:"D",5:"E"}
ar2=np.fromiter(ad,dtype=np.int32)
print(ar2)

### 2. Creating Array By Specific Own  Datatype

In [ ]:
ar2.dtype

In [ ]:
ar2.itemsize

In [ ]:
print(ar2[0],[3])

In [ ]:
ar2[0]

### 3.Arrange() function is used to create array from a range.

In [ ]:
# <arrayname>=numpy.arrange([start],stop,[step],[dtype])

In [ ]:
arr1=np.arange(5)
arr1

In [ ]:
arr2=np.arange(1,7,2,dtype=np.float32)
arr2

### 4.Linespace()function can be used to prepare array of range.

In [ ]:
#arrayname>=numpy.linespace([start],stop,[dtype])

In [ ]:
arr3 = np.linspace(2,3,6)
arr3
# here,an array of 6 values is created between the value 2 and 3

In [ ]:
arr4 = np.linspace(2,5,5,8)
arr4

# 2D NumPy Arrays

In [ ]:
A=np.array([[10,11,12,13],[21,22,23,24]]) # with the help of list,2D array is created
A[1,3] # Accesing Array elements with index

In [ ]:
A[1][3]# Accesing Array elements with index

In [ ]:
A # PRINTING ARRAYS

In [ ]:
print(A)# PRINTING ARRAYS

In [ ]:
type(A),type(a1)

In [ ]:
a1.shape

In [ ]:
A.shape

In [ ]:
A.itemsize

## 2. Creating 2D ndarray using arrange()-

#### in similar manner as we have to created 1D ndarryas with arrange() function,we can also create 2D ndarrays arrange()function along with reshape().

In [ ]:
# <ndarray>.reshape(<shape tuple>)

In [ ]:
ar1=np.arange(10)
ar1

ar3=ar1.reshape(5,2)
ar3

In [ ]:
arr1=np.empty([2,3],dtype=np.int64,order='c')
arr1

In [ ]:
arr1=np.empty([2,3],dtype=np.int64,order='F')
arr1

### Array Slicing

#### it is possible to extract subset of numpy arrays using slices,just like lists

In [25]:
arr=np.array([2,4,6,8,10,12,14,16])
arr[3:7]

array([ 8, 10, 12, 14])

In [26]:
arr[3:7]

array([ 8, 10, 12, 14])

In [27]:
arr[:5]

array([ 2,  4,  6,  8, 10])

In [28]:
arr[:4]

array([2, 4, 6, 8])

In [29]:
arr[:-1]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
arr[-1:]

In [ ]:
arr[2:7:2]

### Joining or Concatentenating Numpy Arrays-

#### for joining or concatenting of two or more existing ndarrays, python provides following functions-
1) hstack() and vstack()
2) concatenate()

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
a1=np.array(list1)
a1

In [ ]:
a2=np.array(list2)
a2

In [ ]:
jion1=np.hstack((a1,a2))
jion1
#hstack method

In [ ]:
jion2=np.vstack((a1,a2))
jion2
# vstack method

## Combibing Existing Arrays Using Concatetenate()-



In [ ]:
a1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a1


In [ ]:
a2=np.array([1,2,3,4,5,6]).reshape(2,3)
a2


In [ ]:
a3=np.array([1,2,3,4,5,6]).reshape(3,2)
a3


In [ ]:
a4=np.array([1,2,3]).reshape(3,1)
a4


In [ ]:
j1=np.concatenate((a1,a2),axis=0)
j1

In [ ]:
j2=np.concatenate((a1,a3),axis=1)
j2

In [ ]:
j3=np.concatenate((a1,a4),axis=1)
j3

## obating subset of array

In [ ]:
ary=np.arange(24.0).reshape(4,6)
ary

In [ ]:
np.hsplit(ary,2)

### Split function

In [7]:
ar1d=[10,11,12,13,14,15,16,17,18,19]
np.split(ar1d,[2,6])

[array([10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])]

In [8]:
ary=np.arange(24.0).reshape(4,6)
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [9]:
np.split(ary,[1,4])
# divided as 0:1 ,1:4,,,4 horizontally(axis=0 becouse skipped)

[array([[0., 1., 2., 3., 4., 5.]]),
 array([[ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([], shape=(0, 6), dtype=float64)]

In [10]:
np.split(ary,[2,5],axis=1)
# divided as 0:2,2:5,5:vertically(axis=1)

[array([[ 0.,  1.],
        [ 6.,  7.],
        [12., 13.],
        [18., 19.]]),
 array([[ 2.,  3.,  4.],
        [ 8.,  9., 10.],
        [14., 15., 16.],
        [20., 21., 22.]]),
 array([[ 5.],
        [11.],
        [17.],
        [23.]])]

In [11]:
np.split(ary,[1,2])

[array([[0., 1., 2., 3., 4., 5.]]),
 array([[ 6.,  7.,  8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])]

In [12]:
np.split(ary,[2,5],axis=0)

[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([], shape=(0, 6), dtype=float64)]

### Extracting Condition Based Non-Contiguous Subsets-

In [13]:
ary

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [14]:
cond=np.mod(ary,5)==0
cond

array([[ True, False, False, False, False,  True],
       [False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False]])

In [15]:
cond=np.mod(ary,7)==0
cond

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False]])

   ##  Arithmatic Operatin of Numpy Array

In [24]:
ary+1.5

array([[ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5, 10.5, 11.5, 12.5],
       [13.5, 14.5, 15.5, 16.5, 17.5, 18.5],
       [19.5, 20.5, 21.5, 22.5, 23.5, 24.5]])

## Covariance Of Numpy Array-

## 1) Covariance

In [21]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,0,-1,-3])
check=np.cov(a,b)
check

array([[ 2.5 , -4.25],
       [-4.25,  8.3 ]])

## 2) Correlation

#### Correlation is basically normalized covariance. it gives two values: 1 if the sets  have postive coveriance and -1 if the datasets have negative covariance.

In [23]:
corr=np.corrcoef(a,b)
corr

array([[ 1.        , -0.93299621],
       [-0.93299621,  1.        ]])